ecommerce/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from user import views as user_view 
from django.contrib.auth import views as auth 
from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('shop/', include('shop.urls')),
    path('login/', include('login.urls')),
    path('',views.user_login)
  
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path, include , re_path
from django.urls import re_path as url
from . import views
from django.urls import path, include

app_name = 'login' 
urlpatterns = [
    url('', views.user_login, name='user_login'),
   
    
   
]

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="ShopHome"),
   
    path("contact/", views.contact, name="ContactUs"),
    path("tracker/", views.tracker, name="TrackingStatus"),
    path("search/", views.search, name="Search"),
    path("products/<int:myid>", views.productView, name="ProductView"),
    path("checkout/", views.checkout, name="Checkout"),
    
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render

def user_login(request):
    if request.method == 'POST':
        
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(username=username, password=password)
    
        
        if user is not None:
            
            login(request, user) 
            return render(request, 'shop/index.html')
        else:
           
            return render(request, 'login/login.html', {'error_message': 'Incorrect username and / or password.'})
    else:
       
        return render(request, 'login/login.html')

    

login/templates/login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ecommerce- Vikas Maurya</title>
   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body class="override">
    <nav class="navbar navbar-inverse" role="navigation">
        < class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/login/login">Ecommerce- Vikas Maurya</a>
            </div>
            
               
            
           
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/login/login">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
   
    <div class="container">
        <div class="row">
            {% block content %}{% endblock %}
        </div>
    </div>
   
   
</body>
</html>

login/templates/login/login.html
{% extends "login/base.html" %}

{% block content %}
    <div class="container">
        <form action="{% url 'login:user_login' %}" method="post">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Login</div>
                    <div class="panel-body">
                        
                            <center>
                                <a href="/shop">Continue With login</a></center>
                       
                        </ul>
                        <br>
                        <br>
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                        <div class="form-group clearfix">
                            <label for="username" class="col-md-4 control-label text-right">Username:</label>
                            <div class="col-md-6">
                                <input name="username" value="" type="text" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="password" class="col-md-4 control-label text-right">Password:</label>
                            <div class="col-md-6">
                                <input name="password" type="password" class="form-control" />
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input name="login" type="submit" value="Login" class="btn btn-success" /> &nbsp;
                            <a href="/user/register">or Register</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}